import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

import Footer from "../components/Footer/Footer.jsx";
import Navbar from "../components/Navber/Navber.jsx";
import Providers from "./lib/providers";
import { ToastContainer } from "react-toastify";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        <Navbar />
        <main className="max-w-7xl mx-auto px-4 w-full">
          <Providers>
             {children}
          </Providers>
        </main>
        <Footer />
       <ToastContainer />
        </body>
    </html>
  );
}
